# Generated by Django 5.2.7 on 2025-10-24 04:49

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('isbn', models.CharField(blank=True, max_length=17, validators=[books.models.validate_isbn], verbose_name='ISBN')),
                ('publication_year', models.IntegerField(validators=[books.models.validate_publication_year], verbose_name='Год публикации')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('non_fiction', 'Нехудожественная литература'), ('science', 'Научная литература'), ('fantasy', 'Фэнтези'), ('mystery', 'Детектив'), ('romance', 'Роман'), ('biography', 'Биография'), ('history', 'История'), ('other', 'Другое')], default='fiction', max_length=20, verbose_name='Жанр')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издательство')),
                ('page_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество страниц')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
