# Generated by Django 5.2.7 on 2025-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Обложка'),
        ),
    ]
