# Generated by Django 5.2.7 on 2025-11-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_type',
        ),
    ]
