# Generated by Django 5.2.7 on 2025-11-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_cover_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='langua',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Язык'),
        ),
    ]
